return {
	["teh"] = "the",
	["lon"] = "lon",
	["bary"] = "barycentric",
	["sou"] = "sou",
	["inportant"] = "important",
	["smh"] = "somehow",
	["with "] = "with",
	["cmplx"] = "complex",
	["tmrw"] = "tomorrow",
	["labeled"] = "labeled",
	["isn"] = "isn",
	["sout"] = "sout",
	["cout"] = "cout",
	["elements"] = "elements",
	["other"] = "other",
	["ii"] = "ii",
	["internet"] = "internet",
	["doesn"] = "doesn",
	["ol"] = "ol",
	["Ag"] = "Ag",
}
