;extends
("*" @operator (#set! conceal "∙"))
("/" @operator (#set! conceal "÷"))
("!" @operator (#set! conceal "¬"))
("||" @keyword.operator (#set! conceal "∪"))
("&&" @keyword.operator (#set! conceal "∩"))
("=" @operator (#set! conceal "←"))
(";" @operator (#set! conceal "𐤟"))
("::" @punctuation.delimiter (#set! conceal "."))
((primitive_type) @type.builtin.cpp (#eq? @type.builtin.cpp "int")
                  (#set! conceal "ℤ"))
((sized_type_specifier) @type.builtin.cpp (#match? @type.builtin.cpp "long ")
                                         (#set! conceal ""))
((primitive_type) @type.builtin.cpp (#eq? @type.builtin.cpp "float")
                  (#set! conceal "ℚ"))
((primitive_type) @type.builtin.cpp (#eq? @type.builtin.cpp "double")
                  (#set! conceal "ℝ"))
;("%" @keyword.operator (#set! conceal "mod"))
